/* Auto-generated by genmsg_cpp for file /home/alatosze/ros_workspace/elektron_kinectbot/elektron_calibration/msg/ScanDistAngle.msg */
#ifndef ELEKTRON_CALIBRATION_MESSAGE_SCANDISTANGLE_H
#define ELEKTRON_CALIBRATION_MESSAGE_SCANDISTANGLE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace elektron_calibration
{
template <class ContainerAllocator>
struct ScanDistAngle_ {
  typedef ScanDistAngle_<ContainerAllocator> Type;

  ScanDistAngle_()
  : header()
  , dist(0.0)
  , angle(0.0)
  {
  }

  ScanDistAngle_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , dist(0.0)
  , angle(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef double _dist_type;
  double dist;

  typedef double _angle_type;
  double angle;


  typedef boost::shared_ptr< ::elektron_calibration::ScanDistAngle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::elektron_calibration::ScanDistAngle_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ScanDistAngle
typedef  ::elektron_calibration::ScanDistAngle_<std::allocator<void> > ScanDistAngle;

typedef boost::shared_ptr< ::elektron_calibration::ScanDistAngle> ScanDistAnglePtr;
typedef boost::shared_ptr< ::elektron_calibration::ScanDistAngle const> ScanDistAngleConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::elektron_calibration::ScanDistAngle_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::elektron_calibration::ScanDistAngle_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace elektron_calibration

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::elektron_calibration::ScanDistAngle_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::elektron_calibration::ScanDistAngle_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::elektron_calibration::ScanDistAngle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3253f279aa8a35d09459ae7f2acf007d";
  }

  static const char* value(const  ::elektron_calibration::ScanDistAngle_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x3253f279aa8a35d0ULL;
  static const uint64_t static_value2 = 0x9459ae7f2acf007dULL;
};

template<class ContainerAllocator>
struct DataType< ::elektron_calibration::ScanDistAngle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "elektron_calibration/ScanDistAngle";
  }

  static const char* value(const  ::elektron_calibration::ScanDistAngle_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::elektron_calibration::ScanDistAngle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float64 dist\n\
float64 angle\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::elektron_calibration::ScanDistAngle_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::elektron_calibration::ScanDistAngle_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::elektron_calibration::ScanDistAngle_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::elektron_calibration::ScanDistAngle_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.dist);
    stream.next(m.angle);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ScanDistAngle_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::elektron_calibration::ScanDistAngle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::elektron_calibration::ScanDistAngle_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "dist: ";
    Printer<double>::stream(s, indent + "  ", v.dist);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ELEKTRON_CALIBRATION_MESSAGE_SCANDISTANGLE_H

